version: '3.7'
services:
  pinns:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/src
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    stdin_open: true
    tty: true
