FROM tensorflow/tensorflow:1.10.1-gpu-py3

WORKDIR "/src"

RUN apt-get update -y && \
    apt-get install -y python3-tk

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY src/ .

CMD [ "python", "./NavierStokes.py" ]
